### ISSUE TITLE
survey-heading changes col-md-X format

### ISSUE THREAD

**Issue by ghost** [toolsforresearch/tfr_responsive#21]
I want the progressbar to be displayed next to the survetitle.

therefore I changed file "survey.pstpl" 

to: 

`<div class="row survey-heading">
    <div class="surveyname col-md-8">
      <img class="mainlogo" src="{TEMPLATEURL}main.png" />
    </div>
    <div class="col-md-4" style="min-height:85px; line-height:85px; ">
        <div class="tfr-progress">
            {PERCENTCOMPLETE}
        </div>
    </div>
</div>`

**but** it has no effect on the actual survey.
Any other change but col-md-12 to col-md-8 does change my html, but somehow the survey changes my col-md-8 back to col-md-12.

Why does it do that? :question:

**Comment by pixelliquid** [comment]
This is because we check for the existence of the language switcher so the layout can adept. If its not present, the `div.survey-heading` gets the class `col-md-12`. You'll have to change that as well. But if you want a multi-language survey you'll have to take the language switcher into account as well.

**Comment by ghost** [comment]
perfect, thanks.
